pool:
  name: Azure Pipelines 
  vmImage: ubuntu
trigger: 
  - master 
jobs:
  - job:  
      steps:  
        - task: Maven@3
          inputs:
            mavenPOMFile: 'pom.xml' 
            goals: 'package'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            mavenVersionOption: 'Default'